.TH "src Directory Reference" 3 "Mon Mar 16 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtsp\&.c\fP"
.br
.RI "Implementation of \fBtsp\&.h\fP functions\&. "
.ti -1c
.RI "file \fBtsp_parser\&.c\fP"
.br
.RI "Parse a TSP problem into a convenient datastructure\&. "
.in -1c
