.TH "CC_GCgraph" 3 "Mon Apr 27 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CC_GCgraph
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBncount\fP"
.br
.ti -1c
.RI "int \fBecount\fP"
.br
.ti -1c
.RI "\fBCC_GCnode\fP * \fBnodelist\fP"
.br
.ti -1c
.RI "\fBCC_GCedge\fP * \fBedgespace\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
