.TH "CC_GHnode" 3 "Mon Apr 27 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CC_GHnode
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBCC_GHnode\fP * \fBparent\fP"
.br
.ti -1c
.RI "struct \fBCC_GHnode\fP * \fBsibling\fP"
.br
.ti -1c
.RI "struct \fBCC_GHnode\fP * \fBchild\fP"
.br
.ti -1c
.RI "double \fBcutval\fP"
.br
.ti -1c
.RI "int \fBndescendants\fP"
.br
.ti -1c
.RI "int \fBspecial\fP"
.br
.ti -1c
.RI "int * \fBnlist\fP"
.br
.ti -1c
.RI "int \fBlistcount\fP"
.br
.ti -1c
.RI "int \fBnum\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
