.TH "CC_SFILE" 3 "Mon May 11 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CC_SFILE
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBstatus\fP"
.br
.ti -1c
.RI "int \fBdesc\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBchars_in_buffer\fP"
.br
.ti -1c
.RI "int \fBcurrent_buffer_char\fP"
.br
.ti -1c
.RI "int \fBbits_in_last_char\fP"
.br
.ti -1c
.RI "int \fBpos\fP"
.br
.ti -1c
.RI "char \fBfname\fP [CC_SFNAME_SIZE]"
.br
.ti -1c
.RI "char \fBhname\fP [CC_SFNAME_SIZE]"
.br
.ti -1c
.RI "unsigned char \fBbuffer\fP [CC_SBUFFER_SIZE]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
