.TH "CC_SRKedge" 3 "Wed Apr 29 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CC_SRKedge
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBCC_SRKnode\fP * \fBend\fP"
.br
.ti -1c
.RI "struct \fBCC_SRKedge\fP * \fBother\fP"
.br
.ti -1c
.RI "struct \fBCC_SRKedge\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBCC_SRKedge\fP * \fBprev\fP"
.br
.ti -1c
.RI "double \fBweight\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
