.TH "CC_SRKnode" 3 "Fri May 8 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CC_SRKnode
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBCC_SRKedge\fP * \fBadj\fP"
.br
.ti -1c
.RI "struct \fBCC_SRKnode\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBCC_SRKnode\fP * \fBprev\fP"
.br
.ti -1c
.RI "struct \fBCC_SRKnode\fP * \fBmembers\fP"
.br
.ti -1c
.RI "struct \fBCC_SRKnode\fP * \fBparent\fP"
.br
.ti -1c
.RI "struct \fBCC_SRKnode\fP * \fBqnext\fP"
.br
.ti -1c
.RI "double \fBprweight\fP"
.br
.ti -1c
.RI "double \fBweight\fP"
.br
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "int \fBnewnum\fP"
.br
.ti -1c
.RI "int \fBonecnt\fP"
.br
.ti -1c
.RI "int \fBonqueue\fP"
.br
.ti -1c
.RI "int \fBmark\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
