.TH "CC_SRKgraph" 3 "Tue May 26 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CC_SRKgraph
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBCC_SRKnode\fP * \fBnodespace\fP"
.br
.ti -1c
.RI "struct \fBCC_SRKedge\fP * \fBedgespace\fP"
.br
.ti -1c
.RI "struct \fBCC_SRKnode\fP * \fBhead\fP"
.br
.ti -1c
.RI "struct \fBCC_SRKedge\fP ** \fBhit\fP"
.br
.ti -1c
.RI "int \fBoriginal_ncount\fP"
.br
.ti -1c
.RI "int \fBoriginal_ecount\fP"
.br
.ti -1c
.RI "int \fBmarker\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
