.TH "CCbigchunkptr" 3 "Thu Apr 23 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCbigchunkptr
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBthis_one\fP"
.br
.ti -1c
.RI "struct CCbigchunk * \fBthis_chunk\fP"
.br
.ti -1c
.RI "struct \fBCCbigchunkptr\fP * \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
