.TH "CCbigguy" 3 "Mon May 4 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCbigguy
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned short \fBihi\fP"
.br
.ti -1c
.RI "unsigned short \fBilo\fP"
.br
.ti -1c
.RI "unsigned short \fBfhi\fP"
.br
.ti -1c
.RI "unsigned short \fBflo\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
