.TH "CCchunk_ineq" 3 "Wed Jun 3 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCchunk_ineq
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int * \fBcoef\fP"
.br
.ti -1c
.RI "int \fBrhs\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
