.TH "CCchunk_intmat" 3 "Fri May 8 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCchunk_intmat
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int * \fBmatrix\fP"
.br
.ti -1c
.RI "CCmatval * \fBfactor\fP"
.br
.ti -1c
.RI "int * \fBcsize\fP"
.br
.ti -1c
.RI "int * \fBrperm\fP"
.br
.ti -1c
.RI "int * \fBcperm\fP"
.br
.ti -1c
.RI "CCmatval * \fBx\fP"
.br
.ti -1c
.RI "CCmatval * \fBbest_x\fP"
.br
.ti -1c
.RI "int \fBnrows\fP"
.br
.ti -1c
.RI "int \fBncols\fP"
.br
.ti -1c
.RI "int \fBrowspace\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
