.TH "CCchunk_fault_callback" 3 "Thu Apr 30 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCchunk_fault_callback
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int(* \fBfunc\fP )(\fBCCchunk_graph\fP *chunk, \fBCCchunk_fault\fP *fault, int *finished, void *u_data)"
.br
.ti -1c
.RI "void * \fBu_data\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
