.TH "CCchunk_localcut_timer" 3 "Thu Apr 30 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCchunk_localcut_timer
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCCchunk_find_timer\fP \fBfind\fP"
.br
.ti -1c
.RI "\fBCCchunk_separate_timer\fP \fBseparate\fP"
.br
.ti -1c
.RI "\fBCCchunk_lift_timer\fP \fBlift\fP"
.br
.ti -1c
.RI "\fBCCutil_timer\fP \fBall\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
