.TH "CCchunklp" 3 "Tue May 26 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCchunklp
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "CClp * \fBlp\fP"
.br
.ti -1c
.RI "int * \fBactive\fP"
.br
.ti -1c
.RI "int * \fBcmatind\fP"
.br
.ti -1c
.RI "double * \fBcmatval\fP"
.br
.ti -1c
.RI "double * \fBpi\fP"
.br
.ti -1c
.RI "int \fBnrows\fP"
.br
.ti -1c
.RI "int \fBextracols\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
