.TH "CCchunk_cut_callback" 3 "Wed Apr 29 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCchunk_cut_callback
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int(* \fBbegin_cut\fP )(void *u_data)"
.br
.ti -1c
.RI "int(* \fBadd_clique\fP )(int *arr, int size, void *u_data)"
.br
.ti -1c
.RI "int(* \fBabort_cut\fP )(void *u_data)"
.br
.ti -1c
.RI "int(* \fBfinish_cut\fP )(int rhs, int *finished, void *u_data)"
.br
.ti -1c
.RI "void * \fBu_data\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
