.TH "CCchunk_flag" 3 "Tue May 26 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCchunk_flag
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBdummy\fP: 1"
.br
.ti -1c
.RI "unsigned \fBpermute\fP: 1"
.br
.ti -1c
.RI "unsigned \fBweighted\fP: 1"
.br
.ti -1c
.RI "unsigned \fBspheres\fP: 1"
.br
.ti -1c
.RI "unsigned \fBuncivilized\fP: 1"
.br
.ti -1c
.RI "unsigned \fBnoshrink\fP: 1"
.br
.ti -1c
.RI "unsigned \fBnolift\fP: 2"
.br
.ti -1c
.RI "unsigned \fBmaxchunksize\fP: 8"
.br
.ti -1c
.RI "unsigned \fBspheresize\fP: 8"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
