.TH "CCdata_user" 3 "Wed Jun 3 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCdata_user
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double * \fBx\fP"
.br
.ti -1c
.RI "double * \fBy\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
