.TH "CCdatagroup" 3 "Tue May 26 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCdatagroup
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int(* \fBedgelen\fP )(int i, int j, struct \fBCCdatagroup\fP *dat)"
.br
.ti -1c
.RI "double * \fBx\fP"
.br
.ti -1c
.RI "double * \fBy\fP"
.br
.ti -1c
.RI "double * \fBz\fP"
.br
.ti -1c
.RI "int ** \fBadj\fP"
.br
.ti -1c
.RI "int * \fBadjspace\fP"
.br
.ti -1c
.RI "int ** \fBlen\fP"
.br
.ti -1c
.RI "int * \fBlenspace\fP"
.br
.ti -1c
.RI "int * \fBdegree\fP"
.br
.ti -1c
.RI "int \fBnorm\fP"
.br
.ti -1c
.RI "int \fBdsjrand_param\fP"
.br
.ti -1c
.RI "int \fBdefault_len\fP"
.br
.ti -1c
.RI "int \fBsparse_ecount\fP"
.br
.ti -1c
.RI "double \fBgridsize\fP"
.br
.ti -1c
.RI "double \fBdsjrand_factor\fP"
.br
.ti -1c
.RI "\fBCCdata_rhvector\fP \fBrhdat\fP"
.br
.ti -1c
.RI "\fBCCdata_user\fP \fBuserdat\fP"
.br
.ti -1c
.RI "int \fBndepot\fP"
.br
.ti -1c
.RI "int \fBorig_ncount\fP"
.br
.ti -1c
.RI "int * \fBdepotcost\fP"
.br
.ti -1c
.RI "int * \fBorig_names\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
