.TH "CCdata_rhvector" 3 "Tue May 26 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCdata_rhvector
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdist_00\fP"
.br
.ti -1c
.RI "int \fBdist_01\fP"
.br
.ti -1c
.RI "int \fBdist_02\fP"
.br
.ti -1c
.RI "int \fBdist_12\fP"
.br
.ti -1c
.RI "int \fBdist_22\fP"
.br
.ti -1c
.RI "double \fBp\fP"
.br
.ti -1c
.RI "int \fBrhlength\fP"
.br
.ti -1c
.RI "char * \fBspace\fP"
.br
.ti -1c
.RI "char ** \fBvectors\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
