.TH "CCedgegengroup" 3 "Wed Apr 29 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCedgegengroup
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBcount\fP"
.br
.ti -1c
.RI "   int \fBquadnearest\fP"
.br
.ti -1c
.RI "   int \fBnearest\fP"
.br
.ti -1c
.RI "   int \fBnearest_start\fP"
.br
.ti -1c
.RI "   int \fBgreedy_start\fP"
.br
.ti -1c
.RI "   int \fBboruvka_start\fP"
.br
.ti -1c
.RI "   int \fBqboruvka_start\fP"
.br
.ti -1c
.RI "   int \fBrandom_start\fP"
.br
.ti -1c
.RI "   int \fBnkicks\fP"
.br
.ti -1c
.RI "} \fBlinkern\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBtwoopt_count\fP"
.br
.ti -1c
.RI "   int \fBtwoopt5_count\fP"
.br
.ti -1c
.RI "   int \fBthreeopt_count\fP"
.br
.ti -1c
.RI "   int \fBgreedy\fP"
.br
.ti -1c
.RI "   int \fBboruvka\fP"
.br
.ti -1c
.RI "   int \fBqboruvka\fP"
.br
.ti -1c
.RI "   int \fBnearest_count\fP"
.br
.ti -1c
.RI "   int \fBrandom_count\fP"
.br
.ti -1c
.RI "} \fBtour\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBwantit\fP"
.br
.ti -1c
.RI "   int \fBbasic\fP"
.br
.ti -1c
.RI "   int \fBpriced\fP"
.br
.ti -1c
.RI "} \fBf2match\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBnumber\fP"
.br
.ti -1c
.RI "   int \fBbasic\fP"
.br
.ti -1c
.RI "   int \fBpriced\fP"
.br
.ti -1c
.RI "} \fBf2match_nearest\fP"
.br
.ti -1c
.RI "int \fBrandom\fP"
.br
.ti -1c
.RI "int \fBwant_tree\fP"
.br
.ti -1c
.RI "int \fBnearest_twomatch_count\fP"
.br
.ti -1c
.RI "int \fBdelaunay\fP"
.br
.ti -1c
.RI "int \fBmlinkern\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
