.TH "CCelistw" 3 "Fri Apr 24 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCelistw
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBecount\fP"
.br
.ti -1c
.RI "int * \fBends\fP"
.br
.ti -1c
.RI "double * \fBweight\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
