.TH "CCgenhash" 3 "Fri May 8 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCgenhash
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnelem\fP"
.br
.ti -1c
.RI "int \fBmaxelem\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int(* \fBhcmp\fP )(void *key1, void *key2, void *u_data)"
.br
.ti -1c
.RI "unsigned int(* \fBhfunc\fP )(void *key, void *u_data)"
.br
.ti -1c
.RI "void * \fBu_data\fP"
.br
.ti -1c
.RI "double \fBmaxdensity\fP"
.br
.ti -1c
.RI "double \fBlowdensity\fP"
.br
.ti -1c
.RI "\fBCCptrworld\fP \fBelem_world\fP"
.br
.ti -1c
.RI "struct CCgenhash_elem ** \fBtable\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
