.TH "ccinfo_t" 3 "Thu Apr 23 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccinfo_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const CPXCENVptr \fBenv\fP"
.br
.ti -1c
.RI "void * \fBcbdata\fP"
.br
.ti -1c
.RI "int \fBwherefrom\fP"
.br
.ti -1c
.RI "int * \fBuseraction_p\fP"
.br
.ti -1c
.RI "\fBcbinfo_t\fP * \fBinfo\fP"
.br
.ti -1c
.RI "const CPXCALLBACKCONTEXTptr \fBcontext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
