.TH "CCkdnode" 3 "Fri May 8 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCkdnode
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBcutval\fP"
.br
.ti -1c
.RI "struct \fBCCkdnode\fP * \fBloson\fP"
.br
.ti -1c
.RI "struct \fBCCkdnode\fP * \fBhison\fP"
.br
.ti -1c
.RI "struct \fBCCkdnode\fP * \fBfather\fP"
.br
.ti -1c
.RI "struct \fBCCkdnode\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBCCkdbnds\fP * \fBbnds\fP"
.br
.ti -1c
.RI "int \fBlopt\fP"
.br
.ti -1c
.RI "int \fBhipt\fP"
.br
.ti -1c
.RI "char \fBbucket\fP"
.br
.ti -1c
.RI "char \fBempty\fP"
.br
.ti -1c
.RI "char \fBcutdim\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
