.TH "CCkdbnds" 3 "Thu Apr 23 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCkdbnds
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBx\fP [2]"
.br
.ti -1c
.RI "double \fBy\fP [2]"
.br
.ti -1c
.RI "struct \fBCCkdbnds\fP * \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
