.TH "CCkdtree" 3 "Wed Apr 29 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCkdtree
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCCkdnode\fP * \fBroot\fP"
.br
.ti -1c
.RI "\fBCCkdnode\fP ** \fBbucketptr\fP"
.br
.ti -1c
.RI "int * \fBperm\fP"
.br
.ti -1c
.RI "\fBCCptrworld\fP \fBkdnode_world\fP"
.br
.ti -1c
.RI "\fBCCptrworld\fP \fBkdbnds_world\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
