.TH "CClk_childnode" 3 "Thu Apr 30 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CClk_childnode
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBCClk_parentnode\fP * \fBparent\fP"
.br
.ti -1c
.RI "struct \fBCClk_childnode\fP * \fBadj\fP [2]"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBname\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
