.TH "CClk_flipper" 3 "Mon May 11 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CClk_flipper
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCClk_parentnode\fP * \fBparents\fP"
.br
.ti -1c
.RI "\fBCClk_childnode\fP * \fBchildren\fP"
.br
.ti -1c
.RI "int \fBreversed\fP"
.br
.ti -1c
.RI "int \fBnsegments\fP"
.br
.ti -1c
.RI "int \fBgroupsize\fP"
.br
.ti -1c
.RI "int \fBsplit_cutoff\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
