.TH "CCpq_tree" 3 "Tue May 26 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCpq_tree
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnodecount\fP"
.br
.ti -1c
.RI "int \fBextern_node\fP"
.br
.ti -1c
.RI "\fBCCpq_node\fP * \fBelems\fP"
.br
.ti -1c
.RI "\fBCCpq_node\fP * \fBleaflist\fP"
.br
.ti -1c
.RI "int \fBmarkbase\fP"
.br
.ti -1c
.RI "\fBCCpq_node\fP \fBpseudo_root\fP"
.br
.ti -1c
.RI "int \fBnode_counter\fP"
.br
.ti -1c
.RI "int \fBnontrivial\fP"
.br
.ti -1c
.RI "\fBCCptrworld\fP \fBpqnode_world\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
