.TH "CCpq_node" 3 "Fri May 8 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCpq_node
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnumber\fP"
.br
.ti -1c
.RI "struct \fBCCpq_node\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBCCpq_elem\fP \fBqueue_elem\fP"
.br
.ti -1c
.RI "\fBCCpq_set\fP \fBchildren_set\fP"
.br
.ti -1c
.RI "\fBCCpq_elem\fP \fBchildren_elem\fP"
.br
.ti -1c
.RI "\fBCCpq_set\fP \fBfull_children_set\fP"
.br
.ti -1c
.RI "\fBCCpq_elem\fP \fBfull_children_elem\fP"
.br
.ti -1c
.RI "\fBCCpq_set\fP \fBpartial_children_set\fP"
.br
.ti -1c
.RI "\fBCCpq_elem\fP \fBpartial_children_elem\fP"
.br
.ti -1c
.RI "\fBCCpq_elem\fP \fBblocked_elem\fP"
.br
.ti -1c
.RI "\fBCCpq_elem\fP \fBleaves_elem\fP"
.br
.ti -1c
.RI "struct \fBCCpq_node\fP * \fBparent\fP"
.br
.ti -1c
.RI "int \fBpertinent_child_count\fP"
.br
.ti -1c
.RI "int \fBpertinent_leaf_count\fP"
.br
.ti -1c
.RI "int \fBmark\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBparenttype\fP"
.br
.ti -1c
.RI "int \fBlabel\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
