.TH "CCpriority" 3 "Wed Apr 29 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCpriority
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fBCCpri_data\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCCdheap\fP \fBheap\fP"
.br
.ti -1c
.RI "union \fBCCpriority::CCpri_data\fP * \fBpri_info\fP"
.br
.ti -1c
.RI "int \fBspace\fP"
.br
.ti -1c
.RI "int \fBfreelist\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
