.TH "CCrandstate" 3 "Mon Apr 27 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCrandstate
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBa\fP"
.br
.ti -1c
.RI "int \fBb\fP"
.br
.ti -1c
.RI "int \fBarr\fP [55]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
