.TH "CCsubdiv" 3 "Thu Apr 23 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCsubdiv
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBxrange\fP [2]"
.br
.ti -1c
.RI "double \fByrange\fP [2]"
.br
.ti -1c
.RI "int \fBcnt\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "double \fBbound\fP"
.br
.ti -1c
.RI "int \fBstatus\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
