.TH "CCsubdiv_lkh" 3 "Fri Apr 24 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCsubdiv_lkh
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBcnt\fP"
.br
.ti -1c
.RI "int \fBstart\fP"
.br
.ti -1c
.RI "double \fBoriglen\fP"
.br
.ti -1c
.RI "double \fBnewlen\fP"
.br
.ti -1c
.RI "int \fBstatus\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
