.TH "CCtsp_tighten_info" 3 "Sun Apr 26 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCtsp_tighten_info
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBncall\fP"
.br
.ti -1c
.RI "int \fBnfail\fP"
.br
.ti -1c
.RI "int \fBnadd\fP"
.br
.ti -1c
.RI "int \fBnadd_tied\fP"
.br
.ti -1c
.RI "int \fBndel\fP"
.br
.ti -1c
.RI "int \fBndel_tied\fP"
.br
.ti -1c
.RI "double \fBadd_delta\fP"
.br
.ti -1c
.RI "double \fBdel_delta\fP"
.br
.ti -1c
.RI "double \fBtime\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
