.TH "CCtsp_xnorm_pricer" 3 "Thu Apr 23 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCtsp_xnorm_pricer
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCCdatagroup\fP * \fBdat\fP"
.br
.ti -1c
.RI "double * \fBpi\fP"
.br
.ti -1c
.RI "int * \fBorder\fP"
.br
.ti -1c
.RI "\fBCCtsp_xnorm_pricer_val\fP * \fBxminuspi_space\fP"
.br
.ti -1c
.RI "\fBCCtsp_xnorm_pricer_val\fP * \fBxminuspi\fP"
.br
.ti -1c
.RI "int * \fBinvxminuspi\fP"
.br
.ti -1c
.RI "int \fBncount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
