.TH "CCtsp_lpgraph" 3 "Wed Apr 29 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCtsp_lpgraph
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBncount\fP"
.br
.ti -1c
.RI "int \fBespace\fP"
.br
.ti -1c
.RI "int \fBecount\fP"
.br
.ti -1c
.RI "int \fBnodemarker\fP"
.br
.ti -1c
.RI "\fBCCtsp_lpnode\fP * \fBnodes\fP"
.br
.ti -1c
.RI "\fBCCtsp_lpedge\fP * \fBedges\fP"
.br
.ti -1c
.RI "\fBCCtsp_lpadj\fP * \fBadjspace\fP"
.br
.ti -1c
.RI "int \fBadjstart\fP"
.br
.ti -1c
.RI "int \fBadjend\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
