.TH "CCtsp_branchobj" 3 "Sun Apr 26 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCtsp_branchobj
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdepth\fP"
.br
.ti -1c
.RI "int \fBrhs\fP"
.br
.ti -1c
.RI "int \fBends\fP [2]"
.br
.ti -1c
.RI "char \fBsense\fP"
.br
.ti -1c
.RI "\fBCCtsp_lpclique\fP * \fBclique\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
