.TH "CCtsp_lpnode" 3 "Tue May 26 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCtsp_lpnode
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdeg\fP"
.br
.ti -1c
.RI "int \fBmark\fP"
.br
.ti -1c
.RI "struct \fBCCtsp_lpadj\fP * \fBadj\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
