.TH "CCtsp_lpcut_in" 3 "Sun Apr 26 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCtsp_lpcut_in
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcliquecount\fP"
.br
.ti -1c
.RI "int \fBdominocount\fP"
.br
.ti -1c
.RI "int \fBrhs\fP"
.br
.ti -1c
.RI "char \fBsense\fP"
.br
.ti -1c
.RI "char \fBbranch\fP"
.br
.ti -1c
.RI "\fBCCtsp_lpclique\fP * \fBcliques\fP"
.br
.ti -1c
.RI "\fBCCtsp_lpdomino\fP * \fBdominos\fP"
.br
.ti -1c
.RI "\fBCCtsp_skeleton\fP \fBskel\fP"
.br
.ti -1c
.RI "struct \fBCCtsp_lpcut_in\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBCCtsp_lpcut_in\fP * \fBprev\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
