.TH "CCtsp_qsparsegroup" 3 "Thu Apr 23 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCtsp_qsparsegroup
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCCdheap\fP * \fBadd_queue\fP"
.br
.ti -1c
.RI "\fBCCdheap\fP * \fBsub_queue\fP"
.br
.ti -1c
.RI "int * \fBcount_m1\fP"
.br
.ti -1c
.RI "int * \fBcount_non0\fP"
.br
.ti -1c
.RI "int * \fBcount_1\fP"
.br
.ti -1c
.RI "int * \fBon_add_queue\fP"
.br
.ti -1c
.RI "int * \fBon_sub_queue\fP"
.br
.ti -1c
.RI "int * \fBmults\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
