.TH "CCtsp_lpcuts" 3 "Thu Apr 30 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCtsp_lpcuts
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcutcount\fP"
.br
.ti -1c
.RI "int \fBsavecount\fP"
.br
.ti -1c
.RI "int \fBcliqueend\fP"
.br
.ti -1c
.RI "int \fBcutspace\fP"
.br
.ti -1c
.RI "int \fBcliquespace\fP"
.br
.ti -1c
.RI "int \fBcliquehashsize\fP"
.br
.ti -1c
.RI "int \fBcliquefree\fP"
.br
.ti -1c
.RI "int * \fBcliquehash\fP"
.br
.ti -1c
.RI "\fBCCtsp_lpcut\fP * \fBcuts\fP"
.br
.ti -1c
.RI "\fBCCtsp_lpclique\fP * \fBcliques\fP"
.br
.ti -1c
.RI "\fBCCgenhash\fP * \fBcuthash\fP"
.br
.ti -1c
.RI "char * \fBtempcuthash\fP"
.br
.ti -1c
.RI "int \fBtempcuthashsize\fP"
.br
.ti -1c
.RI "int \fBdominoend\fP"
.br
.ti -1c
.RI "int \fBdominospace\fP"
.br
.ti -1c
.RI "int \fBdominohashsize\fP"
.br
.ti -1c
.RI "int \fBdominofree\fP"
.br
.ti -1c
.RI "int * \fBdominohash\fP"
.br
.ti -1c
.RI "\fBCCtsp_lpdomino\fP * \fBdominos\fP"
.br
.ti -1c
.RI "double * \fBworkloads\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
