.TH "CCtsp_sparser" 3 "Wed May 27 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCtsp_sparser
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBnode\fP: 24"
.br
.ti -1c
.RI "unsigned int \fBmult\fP: 8"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
