.TH "CCtsp_xnorm_pricer_val" 3 "Wed Apr 29 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCtsp_xnorm_pricer_val
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBval\fP"
.br
.ti -1c
.RI "struct \fBCCtsp_xnorm_pricer_val\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBCCtsp_xnorm_pricer_val\fP * \fBprev\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
