.TH "CCtsp_lp" 3 "Fri May 8 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCtsp_lp
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCCtsp_lpgraph\fP \fBgraph\fP"
.br
.ti -1c
.RI "\fBCCtsp_lpcuts\fP \fBcuts\fP"
.br
.ti -1c
.RI "\fBCCtsp_lpcuts\fP * \fBpool\fP"
.br
.ti -1c
.RI "\fBCCtsp_lpcuts\fP * \fBremotepool\fP"
.br
.ti -1c
.RI "\fBCCtsp_lpcuts\fP * \fBdominopool\fP"
.br
.ti -1c
.RI "CClp * \fBlp\fP"
.br
.ti -1c
.RI "int * \fBperm\fP"
.br
.ti -1c
.RI "\fBCCdatagroup\fP * \fBdat\fP"
.br
.ti -1c
.RI "int \fBfullcount\fP"
.br
.ti -1c
.RI "\fBCCtsp_genadj\fP * \fBfulladj\fP"
.br
.ti -1c
.RI "\fBCCtsp_genadjobj\fP * \fBfulladjspace\fP"
.br
.ti -1c
.RI "int \fBnfixededges\fP"
.br
.ti -1c
.RI "int * \fBfixededges\fP"
.br
.ti -1c
.RI "struct \fBCCtsp_qsparsegroup\fP * \fBsparsifier\fP"
.br
.ti -1c
.RI "int \fBedge_life\fP"
.br
.ti -1c
.RI "int \fBcut_life\fP"
.br
.ti -1c
.RI "char * \fBproblabel\fP"
.br
.ti -1c
.RI "char * \fBprobloc\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBparent_id\fP"
.br
.ti -1c
.RI "int \fBroot\fP"
.br
.ti -1c
.RI "double \fBupperbound\fP"
.br
.ti -1c
.RI "double \fBlowerbound\fP"
.br
.ti -1c
.RI "\fBCCbigguy\fP \fBexact_lowerbound\fP"
.br
.ti -1c
.RI "\fBCCtsp_bigdual\fP * \fBexact_dual\fP"
.br
.ti -1c
.RI "int \fBinfeasible\fP"
.br
.ti -1c
.RI "int \fBfull_edges_valid\fP"
.br
.ti -1c
.RI "CClp_warmstart * \fBwarmstart\fP"
.br
.ti -1c
.RI "\fBCCtsp_lpcut_in\fP \fBcutqueue\fP"
.br
.ti -1c
.RI "\fBCCtsp_lp_result\fP \fBresult\fP"
.br
.ti -1c
.RI "int \fBbranchdepth\fP"
.br
.ti -1c
.RI "\fBCCtsp_branchobj\fP * \fBbranchhistory\fP"
.br
.ti -1c
.RI "\fBCCtsp_cuttree\fP \fBtightcuts\fP"
.br
.ti -1c
.RI "\fBCCtsp_statistics\fP \fBstats\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
