.TH "CCtsp_cutnode" 3 "Fri Apr 24 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCtsp_cutnode
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "struct \fBCCtsp_cutnode\fP * \fBchild\fP"
.br
.ti -1c
.RI "struct \fBCCtsp_cutnode\fP * \fBsibling\fP"
.br
.ti -1c
.RI "struct \fBCCtsp_cutnode\fP * \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
