.TH "CCtsp_cuttree" 3 "Wed Apr 29 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCtsp_cuttree
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnodecount\fP"
.br
.ti -1c
.RI "int \fBextern_node\fP"
.br
.ti -1c
.RI "\fBCCtsp_cutnode\fP * \fBnodelist\fP"
.br
.ti -1c
.RI "\fBCCtsp_cutnode\fP * \fBroot\fP"
.br
.ti -1c
.RI "\fBCCptrworld\fP \fBcutnode_world\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
