.TH "CCtsp_edgegenerator" 3 "Mon Apr 27 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCtsp_edgegenerator
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double * \fBnode_piest\fP"
.br
.ti -1c
.RI "struct \fBCCdatagroup\fP * \fBdg\fP"
.br
.ti -1c
.RI "int * \fBsupply\fP"
.br
.ti -1c
.RI "\fBCCkdtree\fP * \fBkdtree\fP"
.br
.ti -1c
.RI "\fBCCxnear\fP * \fBxnear\fP"
.br
.ti -1c
.RI "struct \fBCCtsp_xnorm_pricer\fP * \fBxprice\fP"
.br
.ti -1c
.RI "\fBCCtsp_genadjobj\fP * \fBadjobjspace\fP"
.br
.ti -1c
.RI "\fBCCtsp_genadj\fP * \fBadj\fP"
.br
.ti -1c
.RI "int \fBncount\fP"
.br
.ti -1c
.RI "int \fBnneighbors\fP"
.br
.ti -1c
.RI "int \fBstart\fP"
.br
.ti -1c
.RI "int \fBcurrent\fP"
.br
.ti -1c
.RI "int \fBsupplyhead\fP"
.br
.ti -1c
.RI "int \fBsupplycount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
