.TH "CCtsp_lpedge" 3 "Wed Apr 29 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCtsp_lpedge
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBends\fP [2]"
.br
.ti -1c
.RI "int \fBfixed\fP"
.br
.ti -1c
.RI "int \fBbranch\fP"
.br
.ti -1c
.RI "int \fBlen\fP"
.br
.ti -1c
.RI "int \fBage\fP"
.br
.ti -1c
.RI "int \fBcoef\fP"
.br
.ti -1c
.RI "int \fBcoefnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
