.TH "CCtsp_cutselect" 3 "Mon May 11 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCtsp_cutselect
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcutpool\fP"
.br
.ti -1c
.RI "int \fBremotepool\fP"
.br
.ti -1c
.RI "char * \fBremotehost\fP"
.br
.ti -1c
.RI "unsigned short \fBremoteport\fP"
.br
.ti -1c
.RI "int \fBdomboss\fP"
.br
.ti -1c
.RI "char * \fBdombosshost\fP"
.br
.ti -1c
.RI "int \fBconnect\fP"
.br
.ti -1c
.RI "int \fBsegments\fP"
.br
.ti -1c
.RI "int \fBexactsubtour\fP"
.br
.ti -1c
.RI "int \fBblockcombs\fP"
.br
.ti -1c
.RI "int \fBgrowcombs\fP"
.br
.ti -1c
.RI "int \fBprclique\fP"
.br
.ti -1c
.RI "int \fBtighten_lp\fP"
.br
.ti -1c
.RI "int \fBteething_lp\fP"
.br
.ti -1c
.RI "int \fBcliquetree_lp\fP"
.br
.ti -1c
.RI "int \fBtighten_pool\fP"
.br
.ti -1c
.RI "int \fBdecker_lp\fP"
.br
.ti -1c
.RI "int \fBdecker_pool\fP"
.br
.ti -1c
.RI "int \fBstar_lp\fP"
.br
.ti -1c
.RI "int \fBstar_pool\fP"
.br
.ti -1c
.RI "int \fBhandling_lp\fP"
.br
.ti -1c
.RI "int \fBhandling_pool\fP"
.br
.ti -1c
.RI "int \fBmaxchunksize\fP"
.br
.ti -1c
.RI "int \fBfilecuts\fP"
.br
.ti -1c
.RI "char * \fBfilecutname\fP"
.br
.ti -1c
.RI "int \fBteething_pool\fP"
.br
.ti -1c
.RI "int \fBfastblossom\fP"
.br
.ti -1c
.RI "int \fBghfastblossom\fP"
.br
.ti -1c
.RI "int \fBexactblossom\fP"
.br
.ti -1c
.RI "int \fBconsecutiveones\fP"
.br
.ti -1c
.RI "int \fBdominos\fP"
.br
.ti -1c
.RI "int \fBshrunk_dominos\fP"
.br
.ti -1c
.RI "int \fBnecklace\fP"
.br
.ti -1c
.RI "int \fBusetighten\fP"
.br
.ti -1c
.RI "int \fBextra_connect\fP"
.br
.ti -1c
.RI "double \fBnexttol\fP"
.br
.ti -1c
.RI "double \fBroundtol\fP"
.br
.ti -1c
.RI "int \fBfastcuts\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
