.TH "CCtsp_PROB_FILE" 3 "Wed Jun 3 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCtsp_PROB_FILE
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCC_SFILE\fP * \fBf\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "char \fBname\fP [CCtsp_PROB_FILE_NAME_LEN]"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBparent\fP"
.br
.ti -1c
.RI "double \fBub\fP"
.br
.ti -1c
.RI "double \fBlb\fP"
.br
.ti -1c
.RI "\fBCCbigguy\fP \fBexactlb\fP"
.br
.ti -1c
.RI "int \fBnnodes\fP"
.br
.ti -1c
.RI "int \fBchild0\fP"
.br
.ti -1c
.RI "int \fBchild1\fP"
.br
.ti -1c
.RI "int \fBreal\fP"
.br
.ti -1c
.RI "int \fBprocessed\fP"
.br
.ti -1c
.RI "int \fBinfeasible\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBdat\fP"
.br
.ti -1c
.RI "   int \fBedge\fP"
.br
.ti -1c
.RI "   int \fBfulladj\fP"
.br
.ti -1c
.RI "   int \fBcut\fP"
.br
.ti -1c
.RI "   int \fBtour\fP"
.br
.ti -1c
.RI "   int \fBbasis\fP"
.br
.ti -1c
.RI "   int \fBnorms\fP"
.br
.ti -1c
.RI "   int \fBfix\fP"
.br
.ti -1c
.RI "   int \fBexactdual\fP"
.br
.ti -1c
.RI "   int \fBhistory\fP"
.br
.ti -1c
.RI "   int \fBwarmstart\fP"
.br
.ti -1c
.RI "} \fBoffsets\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
