.TH "CCtsp_pricegroup" 3 "Tue May 26 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCtsp_pricegroup
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBncount\fP"
.br
.ti -1c
.RI "int \fBespace\fP"
.br
.ti -1c
.RI "int \fBecount\fP"
.br
.ti -1c
.RI "\fBCCtsp_lpnode\fP * \fBnodes\fP"
.br
.ti -1c
.RI "\fBCCtsp_predge\fP * \fBedges\fP"
.br
.ti -1c
.RI "int \fBcliquecount\fP"
.br
.ti -1c
.RI "struct \fBCCtsp_lpclique\fP * \fBcliques\fP"
.br
.ti -1c
.RI "\fBCCtsp_lpgraph\fP * \fBgraph\fP"
.br
.ti -1c
.RI "\fBCCtsp_lpadj\fP * \fBadjspace\fP"
.br
.ti -1c
.RI "double * \fBnode_pi\fP"
.br
.ti -1c
.RI "double * \fBclique_pi\fP"
.br
.ti -1c
.RI "double \fBpenalty\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
