.TH "CCtsp_lpcut" 3 "Wed Apr 29 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCtsp_lpcut
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcliquecount\fP"
.br
.ti -1c
.RI "int \fBdominocount\fP"
.br
.ti -1c
.RI "int \fBmodcount\fP"
.br
.ti -1c
.RI "int \fBage\fP"
.br
.ti -1c
.RI "int \fBrhs\fP"
.br
.ti -1c
.RI "char \fBsense\fP"
.br
.ti -1c
.RI "char \fBbranch\fP"
.br
.ti -1c
.RI "int * \fBcliques\fP"
.br
.ti -1c
.RI "int * \fBdominos\fP"
.br
.ti -1c
.RI "struct \fBCCtsp_sparser\fP * \fBmods\fP"
.br
.ti -1c
.RI "\fBCCtsp_skeleton\fP \fBskel\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
