.TH "CCutil_timer" 3 "Tue May 26 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCutil_timer
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBszeit\fP"
.br
.ti -1c
.RI "double \fBcum_zeit\fP"
.br
.ti -1c
.RI "char \fBname\fP [40]"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
