.TH "CCutil_edgeinf" 3 "Mon May 4 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCutil_edgeinf
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBends\fP [2]"
.br
.ti -1c
.RI "int \fBval\fP"
.br
.ti -1c
.RI "struct \fBCCutil_edgeinf\fP * \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
