.TH "CCverify_cutclass" 3 "Fri May 8 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCverify_cutclass
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBnhandles\fP"
.br
.ti -1c
.RI "int \fBnfamilies\fP"
.br
.ti -1c
.RI "int * \fBcliques\fP"
.br
.ti -1c
.RI "int * \fBinverted\fP"
.br
.ti -1c
.RI "int * \fBfamily_start\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
