.TH "CCxnear" 3 "Fri Apr 24 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCxnear
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBCCdatagroup\fP \fBdat\fP"
.br
.ti -1c
.RI "double * \fBw\fP"
.br
.ti -1c
.RI "int * \fBnodenames\fP"
.br
.ti -1c
.RI "int * \fBinvnames\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
