.TH "configuration" 3 "Wed Apr 15 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
configuration \- Structure to help parsing the command line\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tspconf\&.h>\fP
.SH "Detailed Description"
.PP 
Structure to help parsing the command line\&. 

This structure is used by parse_opt() to store command line arguments as they are being parsed\&.
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP Name of the TSP file to be parsed\&.
.br
\fIname\fP Name to assign to this problem\&. Default: parsed from file\&.
.br
\fIcpxlog\fP Tune information display\&. Default: silent\&.
.br
\fIshouldplot\fP If true, use GnuPlot to draw the tour\&. Default: yes\&.
.br
\fIsolving_method\fP Model/solver to be used\&. Default: Dummy Branch and Bound\&.
.br
\fIthreads\fP Number of threads to use\&. Default: all\&.
.br
\fImemory\fP Maximum amount of memory (in MB) the program may use\&. If the program cannot proceed without requesting more memory, it should be terminated\&. A meaningful value is between 1 and SIZE_MAX\&. Default: no limit\&. Notice that if the real system does not have enough memory, the program may be terminated by the OOM Killer\&.
.br
\fInodelimit\fP Maximum number of nodes the program may visit\&. If the program does not find a solution within these nodes, it should be terminated anyway\&. A meaningful value is between 1 and SIZE_MAX\&. Default: no limit\&.
.br
\fItimelimit\fP Maximum number of seconds the program may run\&. If the program does not terminate within this time, it should be terminated anyway\&. A meaningful value is between 1 and \fBDBL_MAX\fP\&. Default: no limit\&.
.br
\fIcutup\fP Upper cutoff value for the problem\&.
.br
\fIepgap\fP CPLEX optimality gap\&. Default: automatic\&.
.br
\fIseed\fP CPLEX random seed\&. Default: automatic\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
