.TH "configuration" 3 "Fri Apr 10 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
configuration \- Structure to help parsing the command line\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tspconf\&.h>\fP
.SH "Detailed Description"
.PP 
Structure to help parsing the command line\&. 

This structure is used by parse_opt() to store command line arguments as they are being parsed\&.
.PP
\fBParameters:\fP
.RS 4
\fIepgap\fP CPLEX optimality gap\&.
.br
\fIfilename\fP Name of the TSP file to be parsed\&.
.br
\fImemory\fP Maximum amount of memory (in MB) the program may use\&. If the program cannot proceed without requesting more memory, it should be terminated\&. A meaningful value is between 1 and SIZE_MAX\&. Notice that if the real system does not have enough memory, the program may be terminated by the OOM Killer\&.
.br
\fInodelimit\fP Maximum number of nodes the program may visit\&. If the program does not find a solution within these nodes, it should be terminated anyway\&. A meaningful value is between 1 and SIZE_MAX\&.
.br
\fIthreads\fP Number of threads to use\&.
.br
\fItimelimit\fP Maximum number of seconds the program may run\&. If the program does not terminate within this time, it should be terminated anyway\&. A meaningful value is between 1 and \fBDBL_MAX\fP\&.
.br
\fIproblem\fP Pointer to the instance structure to setup\&.
.br
\fIshouldplot\fP If true, use GnuPlot to draw the tour\&. Default: 1\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
