.TH "configuration" 3 "Tue Apr 7 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
configuration \- Structure to help parsing the command line\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBfilename\fP"
.br
.ti -1c
.RI "size_t \fBmemory\fP"
.br
.ti -1c
.RI "size_t \fBthreads\fP"
.br
.ti -1c
.RI "size_t \fBtimelimit\fP"
.br
.ti -1c
.RI "\fBinstance\fP * \fBproblem\fP"
.br
.ti -1c
.RI "int \fBshouldplot\fP"
.br
.ti -1c
.RI "model_t \fBsolving_method\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure to help parsing the command line\&. 

This structure is used by parse_opt() to store command line arguments as they are being parsed\&.
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP Name of the TSP file to be parsed\&.
.br
\fImemory\fP Maximum amount of memory (in MB) the program may use\&. If the program cannot proceed without requesting more memory, it should be terminated\&. A meaningful value is between 1 and SIZE_MAX\&. Notice that if the real system does not have enough memory, the program may be terminated by the OOM Killer\&.
.br
\fIthreads\fP Number of threads to use\&.
.br
\fItimelimit\fP Maximum number of seconds the program may run\&. If the program does not terminate within this time, it should be terminated anyway\&. A meaningful value is between 1 and SIZE_MAX\&.
.br
\fIproblem\fP Pointer to the instance structure to setup\&.
.br
\fIshouldplot\fP If true, use GnuPlot to draw the tour\&. Default: 1\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
