.TH "instance" 3 "Thu Mar 26 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
instance \- Structure to represent a TSP problem\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tsp\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBcutoff\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "unsigned long \fBnnodes\fP"
.br
.ti -1c
.RI "double * \fBxcoord\fP"
.br
.ti -1c
.RI "double * \fBycoord\fP"
.br
.ti -1c
.RI "unsigned long ** \fBsolution\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure to represent a TSP problem\&. 

This structure holds all the useful information to represent and solve a TSP problem\&.
.PP
\fBParameters:\fP
.RS 4
\fIcutoff\fP Master cutoff value of the problem\&.
.br
\fIname\fP Name to give to this problem\&.
.br
\fInnodes\fP Number of nodes\&.
.br
\fIxcoord\fP Pointer to the array with the x coordinates\&.
.br
\fIycoord\fP Pointer to the array with the y coordinates\&.
.br
\fIsolution\fP Pointer to the current solution\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
