.TH "instance" 3 "Thu Mar 19 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
instance \- Structure to store command line arguments\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tsp\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBcutoff\fP"
.br
.ti -1c
.RI "char * \fBfilename\fP"
.br
.ti -1c
.RI "unsigned long long \fBmemory\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "unsigned long \fBnnodes\fP"
.br
.ti -1c
.RI "unsigned int \fBthreads\fP"
.br
.ti -1c
.RI "unsigned long long \fBtimelimit\fP"
.br
.ti -1c
.RI "double * \fBxcoord\fP"
.br
.ti -1c
.RI "double * \fBycoord\fP"
.br
.ti -1c
.RI "unsigned long * \fBsolution\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure to store command line arguments\&. 

This structure is used by parse_opt() to store command line arguments as they are being parsed\&.
.PP
\fBParameters:\fP
.RS 4
\fIcutoff\fP Master cutoff value of the problem\&.
.br
\fIfilename\fP Name of the TSP file to be parsed\&.
.br
\fIloglevel\fP Logging level setting the output verbosity\&.
.br
\fImemory\fP Maximum amount of memory (in MB) the program may use\&. If the program cannot proceed without requesting more memory, it should be terminated\&. A meaningful value is between 1 and ULLONG_MAX\&. Notice that if the real system does not have enough memory, the program may be terminated by the OOM Killer\&.
.br
\fInnodes\fP Number of nodes\&.
.br
\fIthreads\fP Number of threads to use\&.
.br
\fItimelimit\fP Maximum number of seconds the program may run\&. If the program does not terminate within this time, it should be terminated anyway\&. A meaningful value is between 1 and ULLONG_MAX\&.
.br
\fIxcoord\fP Pointer to the array with the x coordinates\&.
.br
\fIycoord\fP Pointer to the array with the y coordinates\&.
.br
\fIsolution\fP Pointer to the current solution\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
