.TH "include/logging.h" 3 "Tue Apr 7 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/logging.h \- Define logging levels\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOG_OFF\fP   0U"
.br
.ti -1c
.RI "#define \fBLOG_FATAL\fP   100U"
.br
.ti -1c
.RI "#define \fBLOG_ERROR\fP   200U"
.br
.ti -1c
.RI "#define \fBLOG_WARN\fP   300U"
.br
.ti -1c
.RI "#define \fBLOG_INFO\fP   400U"
.br
.ti -1c
.RI "#define \fBLOG_DEBUG\fP   500U"
.br
.ti -1c
.RI "#define \fBLOG_TRACE\fP   600U"
.br
.ti -1c
.RI "#define \fBCSUCC\fP   '\\033[92m[+]\\033[0m  '"
.br
.ti -1c
.RI "#define \fBCERROR\fP   '\\033[91m[\-]\\033[0m  '"
.br
.ti -1c
.RI "#define \fBCFATAL\fP   '\\033[31m[!]\\033[0m  '"
.br
.ti -1c
.RI "#define \fBCINFO\fP   '\\033[94m[*]\\033[0m  '"
.br
.ti -1c
.RI "#define \fBCDEBUG\fP   '\\033[96m[\&.]\\033[0m  '"
.br
.ti -1c
.RI "#define \fBCTRACE\fP   '\\033[95m[^]\\033[0m  '"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned \fBloglevel_t\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "loglevel_t \fBloglevel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Define logging levels\&. 


.PP
\fBAuthors:\fP
.RS 4
Francesco Cazzaro, Marco Cieno 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define CDEBUG   '\\033[96m[\&.]\\033[0m  '"
Prefix for INFO logs\&. 
.SS "#define CERROR   '\\033[91m[\-]\\033[0m  '"
Prefix for ERROR logs\&. 
.SS "#define CFATAL   '\\033[31m[!]\\033[0m  '"
Prefix for FATAL logs\&. 
.SS "#define CINFO   '\\033[94m[*]\\033[0m  '"
Prefix for INFO logs\&. 
.SS "#define CSUCC   '\\033[92m[+]\\033[0m  '"
Prefix for SUCCESS logs\&. 
.SS "#define CTRACE   '\\033[95m[^]\\033[0m  '"
Prefix for INFO logs\&. 
.SS "#define LOG_DEBUG   500U"
Debug logging\&. 
.SS "#define LOG_ERROR   200U"
Errors logging\&. 
.SS "#define LOG_FATAL   100U"
Fatals-only logging\&. 
.SS "#define LOG_INFO   400U"
Informative logging\&. 
.SS "#define LOG_OFF   0U"
No logging\&. 
.SS "#define LOG_TRACE   600U"
Verbose debug logging\&. 
.SS "#define LOG_WARN   300U"
Verbose logging\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
