.TH "src/main.c" 3 "Fri Apr 10 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c \- TSP solver\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <argp\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <float\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'logging\&.h'\fP
.br
\fC#include 'tsp\&.h'\fP
.br
\fC#include 'tsp_solvers\&.h'\fP
.br
\fC#include 'tspconf\&.h'\fP
.br
\fC#include 'tspplot\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBparse_tsp_file\fP (const char *, \fBinstance\fP *)"
.br
.RI "Read input TSP file into instance data structure\&. "
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char * \fBargp_program_version\fP = 'TSP solver brought to you by Francesco Cazzaro and Marco Cieno'"
.br
.ti -1c
.RI "const char * \fBargp_program_bug_address\fP = '{marco\&.cieno, francesco\&.cazzaro}@studenti\&.unipd\&.it'"
.br
.in -1c
.SH "Detailed Description"
.PP 
TSP solver\&. 


.PP
\fBAuthors:\fP
.RS 4
Francesco Cazzaro, Marco Cieno 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void parse_tsp_file (const char * filename, \fBinstance\fP * problem)"

.PP
Read input TSP file into instance data structure\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP Name of the file where to read the problem from\&.
.br
\fIproblem\fP Pointer to the problem being parsed\&.
.RE
.PP
\fBWarning:\fP
.RS 4
\fCproblem\fP should be initialized via a call to \fBinit_instance()\fP \fIbefore\fP passing it to this function\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
