.TH "src/tsp.c" 3 "Mon Mar 16 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tsp.c \- Implementation of \fBtsp\&.h\fP functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <errno\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'logging\&.h'\fP
.br
\fC#include 'tsp\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_instance\fP (\fBinstance\fP *problem)"
.br
.RI "Initialize the instance data structure with the default configuration\&. "
.ti -1c
.RI "void \fBdestroy_instance\fP (\fBinstance\fP *problem)"
.br
.RI "Free all the memory and destroy the instance\&. "
.ti -1c
.RI "void \fBrepr_instance\fP (\fBinstance\fP *problem)"
.br
.RI "Pretty-print problem information to \fCstderr\fP according to \fCloglevel\fP verbosity\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implementation of \fBtsp\&.h\fP functions\&. 


.PP
\fBAuthors:\fP
.RS 4
Francesco Cazzaro, Marco Cieno 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void destroy_instance (\fBinstance\fP * problem)"

.PP
Free all the memory and destroy the instance\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&.
.RE
.PP
\fBWarning:\fP
.RS 4
Referencing to problem after calling this function might result in undefined behaviour\&. 
.RE
.PP

.SS "void init_instance (\fBinstance\fP * problem)"

.PP
Initialize the instance data structure with the default configuration\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&. 
.RE
.PP

.SS "void repr_instance (\fBinstance\fP * problem)"

.PP
Pretty-print problem information to \fCstderr\fP according to \fCloglevel\fP verbosity\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
