.TH "include/tsp.h" 3 "Thu Mar 19 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tsp.h \- Type and function definitions for a TSP instance\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'logging\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBinstance\fP"
.br
.RI "Structure to store command line arguments\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_instance\fP (\fBinstance\fP *problem)"
.br
.RI "Initialize the instance data structure with the default configuration\&. "
.ti -1c
.RI "void \fBdestroy_instance\fP (\fBinstance\fP *problem)"
.br
.RI "Free all the memory and destroy the instance\&. "
.ti -1c
.RI "void \fBrepr_instance\fP (\fBinstance\fP *problem)"
.br
.RI "Pretty-print problem information to \fCstderr\fP according to \fCloglevel\fP verbosity\&. "
.ti -1c
.RI "int \fBsolution_cost\fP (\fBinstance\fP *problem)"
.br
.RI "Calculate the cost of the current solution\&. "
.ti -1c
.RI "void \fBdummy_solution\fP (\fBinstance\fP *problem)"
.br
.RI "Generate a random solution for the instance\&. "
.in -1c
.SH "Detailed Description"
.PP 
Type and function definitions for a TSP instance\&. 


.PP
\fBAuthors:\fP
.RS 4
Francesco Cazzaro, Marco Cieno 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void destroy_instance (\fBinstance\fP * problem)"

.PP
Free all the memory and destroy the instance\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&.
.RE
.PP
\fBWarning:\fP
.RS 4
Referencing to problem after calling this function might result in undefined behaviour\&. 
.RE
.PP

.SS "void dummy_solution (\fBinstance\fP * problem)"

.PP
Generate a random solution for the instance\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&. 
.RE
.PP

.SS "void init_instance (\fBinstance\fP * problem)"

.PP
Initialize the instance data structure with the default configuration\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&. 
.RE
.PP

.SS "void repr_instance (\fBinstance\fP * problem)"

.PP
Pretty-print problem information to \fCstderr\fP according to \fCloglevel\fP verbosity\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&. 
.RE
.PP

.SS "int solution_cost (\fBinstance\fP * problem)"

.PP
Calculate the cost of the current solution\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
