.TH "include/tsp.h" 3 "Fri Apr 24 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tsp.h \- Type and function definitions for a TSP instance\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'logging\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBinstance\fP"
.br
.RI "Structure to represent a TSP problem\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_instance\fP (\fBinstance\fP *problem)"
.br
.RI "Initialize the instance data structure with the default configuration\&. "
.ti -1c
.RI "void \fBdestroy_instance\fP (\fBinstance\fP *problem)"
.br
.RI "Free all the memory and destroy the instance\&. "
.ti -1c
.RI "void \fBrepr_instance\fP (\fBinstance\fP *problem)"
.br
.RI "Pretty-print problem information to \fCstderr\fP according to \fCloglevel\fP verbosity\&. "
.ti -1c
.RI "double \fBcompute_solution_cost\fP (\fBinstance\fP *problem)"
.br
.RI "Calculate the cost of the current solution\&. "
.ti -1c
.RI "double \fB_euclidean_distance\fP (double x_a, double y_a, double x_b, double y_b)"
.br
.RI "Calculate the Euclidean distance between two 2-dimensional points\&. "
.in -1c
.SH "Detailed Description"
.PP 
Type and function definitions for a TSP instance\&. 


.PP
\fBAuthors:\fP
.RS 4
Francesco Cazzaro, Marco Cieno 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "double _euclidean_distance (double x_a, double y_a, double x_b, double y_b)"

.PP
Calculate the Euclidean distance between two 2-dimensional points\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx_a\fP X coordinate of first point\&.
.br
\fIy_a\fP Y coordinate of first point\&.
.br
\fIx_b\fP X coordinate of second point\&.
.br
\fIy_a\fP Y coordinate of second point\&. 
.RE
.PP

.SS "double compute_solution_cost (\fBinstance\fP * problem)"

.PP
Calculate the cost of the current solution\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&. 
.RE
.PP

.SS "void destroy_instance (\fBinstance\fP * problem)"

.PP
Free all the memory and destroy the instance\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&.
.RE
.PP
\fBWarning:\fP
.RS 4
Referencing to problem after calling this function might result in undefined behaviour\&. 
.RE
.PP

.SS "void init_instance (\fBinstance\fP * problem)"

.PP
Initialize the instance data structure with the default configuration\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&. 
.RE
.PP

.SS "void repr_instance (\fBinstance\fP * problem)"

.PP
Pretty-print problem information to \fCstderr\fP according to \fCloglevel\fP verbosity\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
