.TH "include/tsp_solvers.h" 3 "Wed Apr 1 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tsp_solvers.h \- Methods for solving a TSP problem\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cplex\&.h>\fP
.br
\fC#include 'tsp\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTSP_SOLVER_RANDOM\fP   1U"
.br
.ti -1c
.RI "#define \fBTSP_SOLVER_DUMMY\fP   2U"
.br
.ti -1c
.RI "#define \fBTSP_SOLVER_MTZ\fP   3U"
.br
.ti -1c
.RI "#define \fBTSP_SOLVER_FLOW1\fP   4U"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned \fBmodel_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBrandom_model\fP (\fBinstance\fP *problem)"
.br
.RI "Generate a random solution for the instance\&. "
.ti -1c
.RI "void \fBdummy_model\fP (\fBinstance\fP *problem)"
.br
.RI "Solve with degree constraints-only model\&. "
.ti -1c
.RI "void \fBmtz_model\fP (\fBinstance\fP *problem)"
.br
.RI "Solve with 'Sequential Formulation' model by Miller, Tucker and Zemlin (1960)\&. "
.ti -1c
.RI "void \fBflow1_model\fP (\fBinstance\fP *problem)"
.br
.RI "Solve with 'Single Commodity Flow' model by Gavish and Graves (1978)\&. "
.in -1c
.SH "Detailed Description"
.PP 
Methods for solving a TSP problem\&. 


.PP
\fBAuthors:\fP
.RS 4
Francesco Cazzaro, Marco Cieno 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define TSP_SOLVER_DUMMY   2U"
Dummy model\&. 
.SS "#define TSP_SOLVER_FLOW1   4U"
Single Commodity Flow model (Gavish and Graves (1978))\&. 
.SS "#define TSP_SOLVER_MTZ   3U"
Sequential Formulation model (Miller, Tucker and Zemlin (1960))\&. 
.SS "#define TSP_SOLVER_RANDOM   1U"
Random model\&. 
.SH "Function Documentation"
.PP 
.SS "void dummy_model (\fBinstance\fP * problem)"

.PP
Solve with degree constraints-only model\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&.
.RE
.PP
\fBNote:\fP
.RS 4
This method does not include subtour elimination constraints\&. 
.RE
.PP

.SS "void flow1_model (\fBinstance\fP * problem)"

.PP
Solve with 'Single Commodity Flow' model by Gavish and Graves (1978)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&. 
.RE
.PP

.SS "void mtz_model (\fBinstance\fP * problem)"

.PP
Solve with 'Sequential Formulation' model by Miller, Tucker and Zemlin (1960)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&. 
.RE
.PP

.SS "void random_model (\fBinstance\fP * problem)"

.PP
Generate a random solution for the instance\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
