.TH "include/tsp_solvers.h" 3 "Sun Mar 22 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tsp_solvers.h \- Methods for solving a TSP problem\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cplex\&.h>\fP
.br
\fC#include 'tsp\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTSP_SOLVER_DUMMY\fP   1"
.br
.ti -1c
.RI "#define \fBTSP_SOLVER_DUMMY_CPLEX\fP   2"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdummy_solution\fP (\fBinstance\fP *problem)"
.br
.RI "Generate a random solution for the instance\&. "
.ti -1c
.RI "void \fBdummy_cplex_solution\fP (\fBinstance\fP *problem)"
.br
.RI "Solve with CPXmipopt\&. "
.ti -1c
.RI "int \fBxpos\fP (unsigned long i, unsigned long j, \fBinstance\fP *problem)"
.br
.RI "Get the position of variable x(i,j) "
.in -1c
.SH "Detailed Description"
.PP 
Methods for solving a TSP problem\&. 


.PP
\fBAuthors:\fP
.RS 4
Francesco Cazzaro, Marco Cieno 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define TSP_SOLVER_DUMMY   1"
Dummy solving method\&. 
.SS "#define TSP_SOLVER_DUMMY_CPLEX   2"
Dummy CPLEX solving method\&. 
.SH "Function Documentation"
.PP 
.SS "void dummy_cplex_solution (\fBinstance\fP * problem)"

.PP
Solve with CPXmipopt\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&.
.RE
.PP
\fBNote:\fP
.RS 4
This method does not include subtour elimination constraints\&. 
.RE
.PP

.SS "void dummy_solution (\fBinstance\fP * problem)"

.PP
Generate a random solution for the instance\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&. 
.RE
.PP

.SS "int xpos (unsigned long i, unsigned long j, \fBinstance\fP * problem)"

.PP
Get the position of variable x(i,j) 
.PP
\fBParameters:\fP
.RS 4
\fIi\fP i in x(i,j)
.br
\fIj\fP j in x(i,j)
.br
\fIproblem\fP Pointer to the instance structure\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
