.TH "tspconf_t" 3 "Mon May 11 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tspconf_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBfilename\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "int \fBshouldplot\fP"
.br
.ti -1c
.RI "model_t \fBsolving_method\fP"
.br
.ti -1c
.RI "size_t \fBthreads\fP"
.br
.ti -1c
.RI "size_t \fBmemory\fP"
.br
.ti -1c
.RI "size_t \fBnodelimit\fP"
.br
.ti -1c
.RI "double \fBtimelimit\fP"
.br
.ti -1c
.RI "double \fBheurtime\fP"
.br
.ti -1c
.RI "double \fBcutup\fP"
.br
.ti -1c
.RI "double \fBepgap\fP"
.br
.ti -1c
.RI "int \fBscrind\fP"
.br
.ti -1c
.RI "int \fBseed\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
