.TH "include/tspconf.h" 3 "Mon May 4 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tspconf.h \- Configuration of a TSP instance that can be applied to CPLEX\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cplex\&.h>\fP
.br
\fC#include 'tsp\&.h'\fP
.br
\fC#include 'tsp_solvers\&.h'\fP
.br
\fC#include 'tspconf\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBtspconf_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtspconf_init\fP ()"
.br
.RI "Initialize the TSP configuration global structure\&. "
.ti -1c
.RI "void \fBtspconf_apply\fP (CPXENVptr env)"
.br
.RI "Apply the global configuration to CPLEX environment\&. "
.ti -1c
.RI "void \fBtspconf_destroy\fP ()"
.br
.RI "Destroy the TSP configuration global structure\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtspconf_t\fP \fBconf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Configuration of a TSP instance that can be applied to CPLEX\&. 


.PP
\fBAuthors:\fP
.RS 4
Francesco Cazzaro, Marco Cieno 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void tspconf_apply (CPXENVptr env)"

.PP
Apply the global configuration to CPLEX environment\&. 
.PP
\fBParameters:\fP
.RS 4
\fIenv\fP Pointer to the CPLEX environment to configure\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
