.TH "include/tspplot.h" 3 "Mon May 11 2020" "TSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tspplot.h \- Type and function definitions for a TSP instance\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'tsp\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinstance_to_plot_dat\fP (\fBinstance\fP *problem, char *outputfile)"
.br
.RI "Write to file the information to plot an instance\&. "
.ti -1c
.RI "void \fBsolution_to_plot_dat\fP (\fBinstance\fP *problem, char *outputfile)"
.br
.RI "Write to file the information to plot the solution of an instance\&. "
.ti -1c
.RI "void \fBplot_instance\fP (\fBinstance\fP *problem)"
.br
.RI "Plot a TSP instance\&. "
.ti -1c
.RI "void \fBplot_solution\fP (\fBinstance\fP *problem)"
.br
.RI "Plot a solved TSP instance\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char * \fBtspplot_tmpfile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type and function definitions for a TSP instance\&. 


.PP
\fBAuthors:\fP
.RS 4
Francesco Cazzaro, Marco Cieno 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void instance_to_plot_dat (\fBinstance\fP * problem, char * outputfile)"

.PP
Write to file the information to plot an instance\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&.
.br
\fIoutputfile\fP Name of the file where to save the plot data\&. 
.RE
.PP

.SS "void plot_instance (\fBinstance\fP * problem)"

.PP
Plot a TSP instance\&. This function will generate a temporary file in the relative path defined by \fCtspplot_tmpfile\fP\&. It will then spawn a gnuplot process and draw on it\&.
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&.
.RE
.PP
\fBNote:\fP
.RS 4
In order for this function to work properly, GnuPlot binary should be compiled with --enable-datastrings and available in the system \fCPATH\fP\&. 
.RE
.PP

.SS "void plot_solution (\fBinstance\fP * problem)"

.PP
Plot a solved TSP instance\&. This function will generate a temporary file in the relative path defined by \fCtspplot_tmpfile\fP\&. It will then spawn a gnuplot process and draw on it\&.
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&.
.RE
.PP
\fBNote:\fP
.RS 4
In order for this function to work properly, GnuPlot binary should be compiled with --enable-datastrings and available in the system \fCPATH\fP\&. 
.RE
.PP

.SS "void solution_to_plot_dat (\fBinstance\fP * problem, char * outputfile)"

.PP
Write to file the information to plot the solution of an instance\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproblem\fP Pointer to the instance structure\&.
.br
\fIoutputfile\fP Name of the file where to save the plot data\&. 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "char* tspplot_tmpfile"
Temporary file to store information for GnuPlot\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for TSP Solver from the source code\&.
